services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: larabrix
    container_name: larabrix-app
    restart: unless-stopped
    volumes:
      - appdata:/var/www
    networks:
      - larabrix

  db:
    image: yobasystems/alpine-mariadb
    container_name: larabrix-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - appdata:/var/www
      - dbdata:/var/lib/mysql
    networks:
      - larabrix

  nginx:
    image: nginx:alpine
    container_name: larabrix-nginx
    restart: unless-stopped
    ports:
      - "127.0.0.1:80:80"
    volumes:
      - ./docker-compose/nginx:/etc/nginx/conf.d
    depends_on:
      - app
    networks:
      - larabrix

networks:
  larabrix:
    driver: bridge
    
volumes:
  dbdata:
  appdata:
